### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Tetrajf** [ksahlin/BESST#22]
Hi There

I've been struggling for a while with install errors. It seems runBESST is installed. I previously got it to work on my mac laptop but I needed more memory so I've tried to install it on a cluster for which I don't have root access. I've have a virtualenv for python 2.7 and have installed LAPACK, BLAS and ATLAS separately (added the path to my bash profile). I installed BESST using pip. There were many warnings during install but no errors and I can call the command.  

I get the following error upon running BESST:

Traceback (most recent call last):
  File "/scratch/sysusers/JF/virtualpython27/py2.7/bin/runBESST", line 395, in <module>
    main(args)
  File "/scratch/sysusers/JF/virtualpython27/py2.7/bin/runBESST", line 73, in main
    from BESST import CreateGraph as CG
  File "/scratch/sysusers/JF/virtualpython27/py2.7/lib/python2.7/site-packages/BESST/CreateGraph.py", line 28, in <module>
    from scipy.stats import ks_2samp
  File "/scratch/sysusers/JF/virtualpython27/py2.7/lib/python2.7/site-packages/scipy/stats/__init__.py", line 321, in <module>
    from .stats import *
  File "/scratch/sysusers/JF/virtualpython27/py2.7/lib/python2.7/site-packages/scipy/stats/stats.py", line 180, in <module>
    import scipy.special as special
  File "/scratch/sysusers/JF/virtualpython27/py2.7/lib/python2.7/site-packages/scipy/special/__init__.py", line 601, in <module>
    from ._ufuncs import *
ImportError: /scratch/sysusers/JF/virtualpython27/py2.7/lib/python2.7/site-packages/scipy/special/_ufuncs.so: undefined symbol: dstevr_

I'd appreciate any help you can provide. It seems from the net that this issue has got to do with my scipy compilation. I'm not sure if the order of which I installed LAPACK, ATLAS and BLAS mattered?

Regards
J

**Comment by ksahlin** [comment]
Hi,

It is indeed the scipy installation that is causing the error. This can be verified if you open python in the terminal and type "import scipy.special as special". Up to my knowledge, this has nothing to do wit LAPACK, BLAS and ATLAS. 

The only thing you _should_ have to do is a clean rebuild of the scipy package (as suggested here:https://github.com/scipy/scipy/issues/2346). From my experience, pip struggles a bit with numpy and scipy packages. If you can reinstall scipy with pip, fine! otherwise you may have to try installing from source (example: http://stackoverflow.com/questions/14179941/how-to-install-python-packages-without-root-privileges) or with a package installer provided by the cluster (e.g. apt-get install for ubuntu). 

Hope this helps,
Kristoffer

**Comment by Tetrajf** [comment]
Thank you very much Kristoffer. 



Sent from my Samsung Galaxy smartphone.

-------- Original message --------
