### ISSUE TITLE
Conflicting scaffold name in output

### ISSUE THREAD

**Issue by melop** [ksahlin/BESST#47]
I noticed that sometimes different scaffolds are assigned the same name in the output. This causes problems for subsequent gapfilling and read mapping. 

I am now bypassing this issue by ranking the scaffolds by size and re-assigning new names, but it would be good to make sure scaffold names are unique.

**Comment by ksahlin** [comment]
This _should_ not happen. Can you please provide more information regarding this. What is the name of the colliding accessions and in what file do yo see the redundancy?

**Comment by ksahlin** [comment]
oh, if BESST scaffolds are fed into besst again, and further scaffolded, it can cause redundancy. This is because BESST leaves the accessions of the contigs/scaffolds that were not linked with any other contig/scaffold in the run. So BESST names the scaffolds as >scaffold_1, >scaffold_2 etc. If the contigs/scaffolds used as input to best have this naming pattern and they are not scaffolded, it can lead to redundancy, I can implement a check for this.

**Comment by ksahlin** [comment]
I'll fix this.

**Comment by melop** [comment]
Right, I think a very simple fix is just to rename everything and output a table listing old and new names, or just check collision. Thanks a lot!
