### ISSUE TITLE
'Graph' object has no attribute 'edge'

### ISSUE THREAD

**Issue by tk2** [ksahlin/BESST#75]
Hi,
I'm trying out BESST on some old mate pair libraries that I'm using to scaffold a pacbio contig assembly. It is reporting an error from the scaffold graph:

Traceback (most recent call last):
  File "../BESST-2.2.4/runBESST", line 415, in <module>
    main(args)
  File "../BESST-2.2.4/runBESST", line 177, in main
    (G, G_prime) = CG.PE(Contigs, Scaffolds, Information, C_dict, param, small_contigs, small_scaffolds, bam_file)      #Create graph, single out too short contigs/scaffolds and store them in F
  File "/nfs/production/mousegenomes/user/tk2/2001-scaffolding/BESST-2.2.4/BESST/CreateGraph.py", line 202, in PE
    CreateEdge(cont_obj1, cont_obj2, scaf_obj1, scaf_obj2, G_prime, param, alignedread, counter, contig1, contig2,save_obs=False)
  File "/nfs/production/mousegenomes/user/tk2/2001-scaffolding/BESST-2.2.4/BESST/CreateGraph.py", line 829, in CreateEdge
    G.edge[(scaf_obj1.name, scaf_side1)][(scaf_obj2.name, scaf_side2)]['obs_sq'] = (obs1 + obs2) ** 2
AttributeError: 'Graph' object has no attribute 'edge'

I'm running with default parameters:
runBESST -c C57BL_6NJ_Polished_Contigs.fasta -f C57BL_6NJ-10kb-mate-pairs-alignment-Sorted.bam --orientation rf

Any ideas or suggestions would be appreciated?

**Comment by ksahlin** [comment]
Hi @tk2,

You're likely running a version of Networkx >= 2.0. BESST is not supported for any Networkx versions 2.0 and above due to big API changes. See Issue #64 

A fix is to uninstall the current networkx version and install a networkx version 1.x. Or if you don't want to tamper with currently installed packages, create a new virtual environment (e.g. with conda) and install besst from scratch as `pip install BESST`. 

Best,
Kristoffer

**Comment by tk2** [comment]
Thanks! Working now.

**Comment by dfpinzons** [comment]
Try to use G.edges(['A','B'])
