### ISSUE TITLE
AttributeError running BESST on test data

### ISSUE THREAD

**Issue by aleuUH** [ksahlin/BESST#80]
Hi

I seemed to have ran into an issue while trying BESST on your testset1 data:
runBESST -c  contigs.fa -f mapped.bam -o ./ -orientation fr
Number of initial contigs: 1836
Choosing mode: 4045
mu_adjusted:4009.235873738282, sigma_adjusted:468.69861482114294, skewness_adjusted:-0.3115836279662499
Creating contig graph with library:  mapped.bam
Too fragmented assembly (given the insert size of the library)                  for statistical scoring. Proceding with path finding.Constructed contig graph. Start BESST algorithm for creating scaffolds.
Traceback (most recent call last):
  File "/home/leu2/e/genome_finish/bin/runBESST", line 421, in <module>
    main(args)
  File "/home/leu2/e/genome_finish/bin/runBESST", line 199, in main
    MS.Algorithm(G, G_prime, Contigs, small_contigs, Scaffolds, small_scaffolds, Information, param)   # Make scaffolds, store the complex areas (consisting of contig/scaffold) in F, store the created scaffolds in Scaffolds, update Contigs
  File "/home/leu2/e/genome_finish/lib/python3.7/site-packages/BESST/MakeScaffolds.py", line 52, in Algorithm
    for edge in G.edges_iter():
AttributeError: 'Graph' object has no attribute 'edges_iter'

Any idea why that is?

Thank you

**Comment by aleuUH** [comment]
BESST was installed via conda

**Comment by ksahlin** [comment]
Hi @aleuUH,

Yes, I do :) You're probably running a version of Networkx >= 2.0. BESST is not supported for any Networkx versions 2.0 and above due to big API changes. See Issue #75 and #64.

A fix is to uninstall the current networkx version and install a networkx version 1.x. 

If you don't want to tamper with currently installed packages, create a new virtual environment for BESST (e.g. with conda) and install BESST from scratch in this environment as `pip install BESST`.

Best,
K

**Comment by aleuUH** [comment]
Awesome! switching over to pip install with python2.7 seems to work.

Thanks!

**Comment by ksahlin** [comment]
Great!
